import { z } from 'zod';

// ---------------------------------------------------------------------------
// Enums / literals
// ---------------------------------------------------------------------------

export const PMSSourceSchema = z.enum([
  'mews',
  'cloudbeds',
  'opera',
  'hotelrunner',
  'electro',
]);
export type PMSSource = z.infer<typeof PMSSourceSchema>;

export const BedTypeSchema = z.enum([
  'single',
  'double',
  'twin',
  'king',
  'queen',
  'bunk',
  'sofa',
  'unknown',
]);
export type BedType = z.infer<typeof BedTypeSchema>;

// ---------------------------------------------------------------------------
// Canonical room type schema
// ---------------------------------------------------------------------------

export const CanonicalRoomTypeSchema = z.object({
  /** Internal stable identifier (generated by the adapter) */
  id: z.string(),

  /** Original identifier from the source PMS */
  externalId: z.string(),

  /** Which PMS this record came from */
  pmsSource: PMSSourceSchema,

  /** Human-readable room type name */
  name: z.string(),

  /** Short code / abbreviation used in the PMS */
  shortCode: z.string(),

  /** Full description of the room type */
  description: z.string(),

  /** Maximum number of guests allowed */
  maxOccupancy: z.number().int().nonnegative(),

  /** Default/standard occupancy for this room type */
  defaultOccupancy: z.number().int().nonnegative(),

  /** Bed configuration */
  bedType: BedTypeSchema,

  /** Number of physical rooms of this type in inventory */
  roomCount: z.number().int().nonnegative(),

  /** List of amenities included */
  amenities: z.array(z.string()),

  /** Whether the room type is currently active / sellable */
  isActive: z.boolean(),

  /**
   * Completeness score: 0.0–1.0.
   * Reflects how many of the canonical fields were populated from source data
   * (vs. filled with defaults). Useful for data quality monitoring.
   */
  confidence: z.number().min(0).max(1),

  /** Full original payload from the PMS for debugging / audit */
  rawData: z.record(z.string(), z.unknown()),
});

export type CanonicalRoomType = z.infer<typeof CanonicalRoomTypeSchema>;
